backend = "glx";

#OPACITY
inactive-opacity = 0.8;
frame-opacity = 0.7;

opacity-rule = [
  "100:class_g = 'firefox' && !focused",
  "80:class_g = 'kitty'"
]

#ROUNDED COURNER
corner-radius = 15;

#BLURRING
blur:
{
    method = "dual_kawase";
    size = 10;
    strength = 5;
};

blur-background-exclude = [
  "class_g = 'slop'"
];

#SHADOWS
shadow = true;
shadow-radius = 1; #blur radius
shadow-opacity = .1;
shadow-offset-x = 0;
shadow-offset-y = 0;

#FADING
# fading = true;
# fade-delta = 7;

#ANIMATIONS
animations = ({
  # Pop in
  duration = 0.2;
  initial-scale = 0.8;
  triggers = ["open", "show"];
  anim-curve = {
        curve = "cubic-bezier(0, 1.5, 1, 1)";
        start = 0;
        end = 1;
        duration = "duration";
  }
  scale-x = "anim-curve * (1 - initial-scale) + initial-scale";
  scale-y = "anim-curve * (1 - initial-scale) + initial-scale";
  offset-x = "(1 - scale-x) / 2 * window-width";
  offset-y = "(1 - scale-y) / 2 * window-height";
  opacity = "anim-curve";
  shadow-offset-x = "offset-x";
  shadow-offset-y = "offset-y";
  shadow-scale-x = "scale-x";
  shadow-scale-y = "scale-y";
}, {
  # Pop out
  duration = 0.1;
  initial-scale = 0.8;
  triggers = ["hide", "close"];
  anim-curve = {
        curve = "cubic-bezier(0, 0, 1, -0.5)";
        start = 1;
        end = 0;
        duration = "duration";
  }
  scale-x = "anim-curve * (1 - initial-scale) + initial-scale";
  scale-y = "anim-curve * (1 - initial-scale) + initial-scale";
  offset-x = "(1-scale-x) / 2 * window-width";
  offset-y = "(1-scale-y) / 2 * window-height";
  opacity = "anim-curve";
  shadow-offset-x = "offset-x";
  shadow-offset-y = "offset-y";
  shadow-scale-x = "scale-x";
  shadow-scale-y = "scale-y";
}, {
  triggers = ["geometry"];
  preset = "geometry-change";
  duration = 0.2;
})

#OTHERS
vsync = true
